### ISSUE TITLE
No modules decoupling

### ISSUE THREAD

**Issue by luislukas** [jonneymendoza/movieList#1]
The main issue is again no decoupling of the `modules`
https://github.com/jonneymendoza/movieList/blob/17a7e753c25438a2bec2cb686389659cb50f1d06/app/src/main/java/com/richards/jonathan/movielist/main/MovieListApp.kt#L12

**Comment by jonneymendoza** [comment]
You can Decouple this easily mate.  I just loaded it this way to keep things simple but you can create whatever DI modular strategy that suits fit, such as having just a DomainModule, DataModule, UIModule etc that determins the level in Clear Architecture, or go a level down have a module for usecases, one for viewmodels etc etc its really up to the dev and not a limitation of Koin @luislukas
